apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  activeDeadlineSeconds: 3  # job이 최대 실행될 수 있는 타임아웃 시간을 줌. 즉,job이 pod를 생성할 때 3초를 넘기면 실패로 간주 
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: hello
        image: ubuntu:focal
        command: ["sh", "-c", "sleep 5; echo Hello World!"]